os: linux
dist: xenial
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.7
  - 3.8
  - 3.9
  - pypy
  - pypy3
jobs:
  include:
    - python: 2.7
      env: PYTEST_ADDOPTS='--cov mpmath'
    - python: 3.6
      env: PYTEST_ADDOPTS='--cov mpmath'
before_install:
  - pip install -U --force-reinstall setuptools
install:
  - pip install -U -e .[develop]
script:
  # Guard against invalid escapes in strings, like '\s'.
  - python -We:invalid -m compileall -f mpmath -q
  - pycodestyle
  - py.test
after_success: test -n "${PYTEST_ADDOPTS}" && codecov
notifications:
  email: false
