language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.7-dev
  - 3.8-dev
  - pypy
  - pypy3.5
matrix:
  include:
    - python: 2.7
      env: COVERAGE='on'
    - python: 3.6
      env: COVERAGE='on'
    - python: 3.4
      before_install:
        - pip install --upgrade --force-reinstall setuptools
install:
  - pip install -U -e .[develop]
script:
  # Guard against invalid escapes in strings, like '\s'.
  - python -We:invalid -m compileall -f mpmath -q
  - pycodestyle
  - |
    if [ -n "${COVERAGE}" ]; then
      py.test --cov mpmath
    else
      py.test
    fi
after_success: test -n "${COVERAGE}" && codecov
notifications:
  email: false
